import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '4° Entrega',
  description: 'Generated by 4° Entrega',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        
        <header className='bg-gray-700 text-white'>
        <h2 className='text-center'>Meus Produtos</h2>
        <ul>
          <li><Link href="/">Home</Link></li>
          <li><Link href="/produtos/tenis">Tênis</Link></li>
          <li><Link href="/produtos/calca">Calca</Link></li>
          <li><Link href="/produtos/meia">Meia</Link></li>
          <li><Link href="/produtos/camisa">Camisa</Link></li>
        </ul>  
        </header>

        {children}
        
        </body>
    </html>
  )
}
